-- Tarea 1: Crear y popular la DB

CREATE TABLE lyfter_car_rental.users
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL,
    username VARCHAR(25) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_username UNIQUE (username),
    CONSTRAINT chk_birthdate CHECK (birthdate <= CURRENT_DATE),
    CONSTRAINT chk_user_status CHECK (status IN ('Active', 'Inactive', 'Suspended'))
);

ALTER TABLE IF EXISTS lyfter_car_rental.users
    OWNER TO postgres;


INSERT INTO lyfter_car_rental.users
(name, last_name, username, email, password, birthdate, status)
VALUES
('John', 'Smith', 'johnsmith', 'johnsmith@email.com', 'J0hn#2024!', '1990-05-12', 'Active'),
('Emma', 'Johnson', 'emmaj', 'emmaj@email.com', 'Emma@8921', '1992-08-23', 'Active'),
('Michael', 'Brown', 'mbrown', 'mbrown@email.com', 'M!chael77', '1988-03-15', 'Inactive'),
('Sophia', 'Davis', 'sophiad', 'sophiad@email.com', 'Soph!a456', '1995-11-02', 'Active'),
('William', 'Miller', 'wmiller', 'wmiller@email.com', 'Will#1987', '1987-07-19', 'Active'),
('Olivia', 'Wilson', 'oliviaw', 'oliviaw@email.com', 'Oliv!a998', '1998-01-30', 'Active'),
('James', 'Moore', 'jmoore', 'jmoore@email.com', 'James@341', '1991-09-18', 'Inactive'),
('Ava', 'Taylor', 'avat', 'avat@email.com', 'Ava#7821', '1997-04-22', 'Active'),
('Benjamin', 'Anderson', 'banderson', 'banderson@email.com', 'Benj@1989', '1989-12-05', 'Active'),
('Isabella', 'Thomas', 'isabellat', 'isabellat@email.com', 'Isa!bella44', '1994-06-11', 'Active'),

('Lucas', 'Jackson', 'lucasj', 'lucasj@email.com', 'Lucas#555', '1993-02-14', 'Active'),
('Mia', 'White', 'miawhite', 'miawhite@email.com', 'Mia@2025', '1996-10-08', 'Inactive'),
('Henry', 'Harris', 'henryh', 'henryh@email.com', 'Henry!808', '1985-05-21', 'Active'),
('Charlotte', 'Martin', 'charlottem', 'charlottem@email.com', 'Char#9900', '1999-03-09', 'Active'),
('Alexander', 'Thompson', 'alexth', 'alexth@email.com', 'Alex!12345', '1990-11-25', 'Active'),
('Amelia', 'Garcia', 'ameliag', 'ameliag@email.com', 'Amel!a765', '1997-07-17', 'Inactive'),
('Daniel', 'Martinez', 'danielm', 'danielm@email.com', 'Dan#741852', '1992-01-04', 'Active'),
('Harper', 'Robinson', 'harperr', 'harperr@email.com', 'Harp!er357', '1998-12-20', 'Active'),
('Matthew', 'Clark', 'mattc', 'mattc@email.com', 'Matt#2468', '1986-08-13', 'Active'),
('Evelyn', 'Rodriguez', 'evelynr', 'evelynr@email.com', 'Eve!2024', '1994-09-29', 'Inactive'),

('Joseph', 'Lewis', 'jlewis', 'jlewis@email.com', 'Joe#1122', '1991-06-15', 'Active'),
('Abigail', 'Lee', 'abigaill', 'abigaill@email.com', 'Abi!8899', '1995-02-27', 'Active'),
('Samuel', 'Walker', 'samwalker', 'samwalker@email.com', 'Sam#7788', '1988-04-18', 'Active'),
('Emily', 'Hall', 'emilyh', 'emilyh@email.com', 'Emily!123', '1993-10-11', 'Inactive'),
('David', 'Allen', 'dallen', 'dallen@email.com', 'Dav!d5678', '1987-12-22', 'Active'),
('Ella', 'Young', 'ellay', 'ellay@email.com', 'Ella#4545', '1999-05-07', 'Active'),
('Christopher', 'King', 'cking', 'cking@email.com', 'Chris!321', '1990-07-03', 'Active'),
('Scarlett', 'Wright', 'scarlettw', 'scarlettw@email.com', 'Scar#9876', '1996-01-19', 'Inactive'),
('Andrew', 'Scott', 'andrews', 'andrews@email.com', 'Andy!654', '1989-09-14', 'Active'),
('Grace', 'Green', 'graceg', 'graceg@email.com', 'Grace#741', '1997-11-28', 'Active'),

('Joshua', 'Baker', 'joshuab', 'joshuab@email.com', 'Josh!258', '1992-03-16', 'Active'),
('Chloe', 'Adams', 'chloea', 'chloea@email.com', 'Chloe#369', '1998-06-21', 'Inactive'),
('Ryan', 'Nelson', 'ryann', 'ryann@email.com', 'Ryan!753', '1985-10-30', 'Active'),
('Victoria', 'Carter', 'victoriac', 'victoriac@email.com', 'Vic#8520', '1994-12-10', 'Active'),
('Nathan', 'Mitchell', 'nathanm', 'nathanm@email.com', 'Nate!4567', '1991-04-01', 'Active'),
('Lily', 'Perez', 'lilyp', 'lilyp@email.com', 'Lily#951', '1997-08-25', 'Inactive'),
('Aaron', 'Roberts', 'aaronr', 'aaronr@email.com', 'Aar!on852', '1988-02-06', 'Active'),
('Hannah', 'Turner', 'hannaht', 'hannaht@email.com', 'Han#9632', '1995-09-12', 'Active'),
('Christian', 'Phillips', 'christianp', 'christianp@email.com', 'Chris!7410', '1990-01-31', 'Active'),
('Zoe', 'Campbell', 'zoec', 'zoec@email.com', 'Zoe#1597', '1998-04-17', 'Inactive'),

('Jonathan', 'Parker', 'jonathanp', 'jonathanp@email.com', 'Jon!7531', '1987-06-08', 'Active'),
('Nora', 'Evans', 'norae', 'norae@email.com', 'Nora#4862', '1996-11-04', 'Active'),
('Brandon', 'Edwards', 'brandone', 'brandone@email.com', 'Brand!258', '1993-07-23', 'Active'),
('Aria', 'Collins', 'ariac', 'ariac@email.com', 'Aria#7410', '1999-02-15', 'Inactive'),
('Tyler', 'Stewart', 'tylers', 'tylers@email.com', 'Tyler!852', '1989-05-27', 'Active'),
('Layla', 'Sanchez', 'laylas', 'laylas@email.com', 'Layla#963', '1994-08-09', 'Active'),
('Kevin', 'Morris', 'kevinm', 'kevinm@email.com', 'Kev!n3579', '1991-10-05', 'Active'),
('Avery', 'Rogers', 'averyr', 'averyr@email.com', 'Avery#654', '1997-03-20', 'Inactive'),
('Justin', 'Reed', 'justinr', 'justinr@email.com', 'Just!n258', '1986-12-14', 'Active'),
('Natalie', 'Cook', 'nataliec', 'nataliec@email.com', 'Nat#741852', '1995-07-01', 'Active');


CREATE TABLE lyfter_car_rental.cars
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    manufacturing_year INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Available',

    CONSTRAINT pk_cars PRIMARY KEY (id),

    CONSTRAINT chk_car_status
        CHECK (status IN ('Available', 'Rented', 'Maintenance')),

    CONSTRAINT chk_manufacturing_year
        CHECK (
            manufacturing_year >= 1900
            AND manufacturing_year <= EXTRACT(YEAR FROM CURRENT_DATE)
        )
);

ALTER TABLE IF EXISTS lyfter_car_rental.cars
    OWNER TO postgres;


INSERT INTO lyfter_car_rental.cars
(brand, model, manufacturing_year, status)
VALUES
('Toyota', 'Corolla', 2022, 'Available'),
('Toyota', 'Yaris', 2021, 'Available'),
('Toyota', 'RAV4', 2023, 'Rented'),
('Toyota', 'Hilux', 2020, 'Available'),
('Honda', 'Civic', 2022, 'Available'),
('Honda', 'Accord', 2021, 'Rented'),
('Honda', 'CR-V', 2023, 'Available'),
('Honda', 'Pilot', 2020, 'Maintenance'),
('Hyundai', 'Elantra', 2022, 'Available'),
('Hyundai', 'Tucson', 2021, 'Rented'),

('Hyundai', 'Santa Fe', 2023, 'Available'),
('Hyundai', 'Venue', 2020, 'Available'),
('Kia', 'Rio', 2022, 'Available'),
('Kia', 'Sportage', 2021, 'Maintenance'),
('Kia', 'Sorento', 2023, 'Available'),
('Kia', 'Seltos', 2022, 'Rented'),
('Nissan', 'Sentra', 2021, 'Available'),
('Nissan', 'Versa', 2020, 'Available'),
('Nissan', 'X-Trail', 2023, 'Rented'),
('Nissan', 'Frontier', 2022, 'Available'),

('Mazda', 'Mazda3', 2021, 'Available'),
('Mazda', 'CX-5', 2023, 'Maintenance'),
('Mazda', 'CX-30', 2022, 'Available'),
('Chevrolet', 'Onix', 2021, 'Available'),
('Chevrolet', 'Tracker', 2023, 'Rented'),
('Chevrolet', 'Captiva', 2020, 'Available'),
('Ford', 'Focus', 2021, 'Available'),
('Ford', 'Escape', 2022, 'Maintenance'),
('Ford', 'Explorer', 2023, 'Available'),
('Ford', 'Ranger', 2020, 'Rented'),

('Volkswagen', 'Jetta', 2022, 'Available'),
('Volkswagen', 'Tiguan', 2023, 'Available'),
('Volkswagen', 'Taos', 2021, 'Rented'),
('BMW', 'X1', 2022, 'Available'),
('BMW', 'X3', 2023, 'Maintenance'),
('BMW', 'X5', 2021, 'Available'),
('Mercedes-Benz', 'GLA 200', 2022, 'Available'),
('Mercedes-Benz', 'GLC 300', 2023, 'Rented'),
('Mercedes-Benz', 'GLE 450', 2021, 'Available'),
('Audi', 'A3', 2022, 'Available'),

('Audi', 'Q3', 2023, 'Maintenance'),
('Audi', 'Q5', 2021, 'Available'),
('Jeep', 'Compass', 2022, 'Rented'),
('Jeep', 'Cherokee', 2021, 'Available'),
('Jeep', 'Wrangler', 2023, 'Available'),
('Subaru', 'Impreza', 2022, 'Available'),
('Subaru', 'Forester', 2021, 'Maintenance'),
('Subaru', 'Outback', 2023, 'Available'),
('Mitsubishi', 'ASX', 2022, 'Rented'),
('Mitsubishi', 'L200', 2021, 'Available');


CREATE TABLE lyfter_car_rental.rentals
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    user_id INTEGER NOT NULL,
    car_id INTEGER NOT NULL,

    rental_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    rental_status VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT pk_rentals PRIMARY KEY (id),

    CONSTRAINT fk_rentals_user
        FOREIGN KEY (user_id)
        REFERENCES lyfter_car_rental.users(id),

    CONSTRAINT fk_rentals_car
        FOREIGN KEY (car_id)
        REFERENCES lyfter_car_rental.cars(id),

    CONSTRAINT chk_rental_status
        CHECK (rental_status IN ('Active', 'Completed'))
);

ALTER TABLE IF EXISTS lyfter_car_rental.rentals
    OWNER TO postgres;


INSERT INTO lyfter_car_rental.rentals
(user_id, car_id, rental_status)
VALUES
(1, 3, 'Active'),
(2, 6, 'Completed'),
(3, 10, 'Completed'),
(4, 16, 'Active'),
(5, 19, 'Completed'),
(6, 25, 'Completed'),
(7, 30, 'Completed'),
(8, 33, 'Active'),
(9, 38, 'Completed'),
(10, 43, 'Active'),

(11, 46, 'Completed'),
(12, 49, 'Completed'),
(13, 1, 'Completed'),
(14, 2, 'Completed'),
(15, 4, 'Active'),
(16, 5, 'Completed'),
(17, 7, 'Completed'),
(18, 8, 'Active'),
(19, 9, 'Completed'),
(20, 11, 'Completed'),

(21, 12, 'Completed'),
(22, 13, 'Active'),
(23, 14, 'Completed'),
(24, 15, 'Completed'),
(25, 17, 'Active'),
(26, 18, 'Completed'),
(27, 20, 'Completed'),
(28, 21, 'Completed'),
(29, 23, 'Active'),
(30, 24, 'Completed'),

(31, 26, 'Completed'),
(32, 27, 'Active'),
(33, 28, 'Completed'),
(34, 29, 'Completed'),
(35, 31, 'Completed'),
(36, 32, 'Completed'),
(37, 34, 'Active'),
(38, 35, 'Completed'),
(39, 36, 'Completed'),
(40, 37, 'Active'),

(41, 39, 'Completed'),
(42, 40, 'Completed'),
(43, 41, 'Active'),
(44, 42, 'Completed'),
(45, 44, 'Completed'),
(46, 45, 'Active'),
(47, 47, 'Completed'),
(48, 48, 'Completed'),
(49, 50, 'Active'),
(50, 22, 'Completed');